# Generated by Django 5.1.11 on 2025-07-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recurringtransaction_savingsgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='notnotes',
            new_name='notes',
        ),
    ]
