# Generated by Django 5.1.11 on 2025-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_notnotes_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
