# Generated by Django 5.1.11 on 2025-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, help_text='Optional: Enter your bank account number for reference', max_length=20, null=True, unique=True),
        ),
    ]
