# Generated by Django 5.2.4 on 2025-07-16 08:36

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_receipt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='receipts/'),
        ),
    ]
