# Generated by Django 5.1.11 on 2025-07-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ocr_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
